### ISSUE TITLE
Auto detect the public IP address

### ISSUE THREAD

**Issue by antho1404** [ilgooz/service-location#2]
We need to add the IP in the locate task, it could be good to get the knowledge of this IP because it's kind of complicated to know your IP.

I see 2 solutions for that:
- IP as optional attribute
- new task get IP

We can use apis like https://www.ipify.org/ to get the public IP

**Comment by ilgooz** [comment]
What if _service-location_ service is deployed to another peer in the network? In that case we're no longer be able to get the public IP address of _service_ that requested the location info. And, in that case, location info we get will be belong to peer that _service-location_ is deployed.

**Comment by antho1404** [comment]
This feature can be really helpful to actually know the IP of all the peers but I agree that this might not be related to this service
